// Generated by scripts/tmbox_flows.py from the server-16x2 engine; do not edit.
// tests/test_tmbox_flows.py fails when the engine and this file disagree.
globalThis.TMBoxFlows = {
 "profile": "server-16x2",
 "clock": "12:34",
 "stations": [
  {
   "code": "SVM",
   "name": "Sölvmora"
  },
  {
   "code": "KNB",
   "name": "Knastebo"
  },
  {
   "code": "DY",
   "name": "Dimmeby"
  }
 ],
 "flows": [
  {
   "id": "klarera",
   "title": "Klartecken, avgång och ankomst",
   "mode": "Med klartecken",
   "intro": "Det vanliga flödet på en sträcka med klartecken: avsändaren begär, mottagaren ger klart, avsändaren rapporterar avgång och mottagaren tar emot.",
   "setup": null,
   "boxes": [
    {
     "id": "KNB",
     "code": "KNB",
     "label": "KNB",
     "station": "Knastebo"
    },
    {
     "id": "DY",
     "code": "DY",
     "label": "DY",
     "station": "Dimmeby"
    }
   ],
   "start": [
    {
     "box": "KNB",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "DY",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "KNB",
     "keys": [
      "3",
      "9"
     ],
     "wait": null,
     "caption": "Skriv tågnumret direkt från översikten. Siffrorna stannar i boxen tills du trycker #.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "TÅG: 39___      ",
        "#Sök B:Del 12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Sök tåg (begär direkt)"
      ],
      [
       "*",
       "Avbryt inmatning"
      ],
      [
       "A",
       "Förfrågningskö (avbryt inmatning)"
      ],
      [
       "B",
       "Sudda siffra"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# söker tåget och begär klartecken (?) i samma tryck. 39 ska till Dimmeby, som står i översikten och visar förfrågan direkt. * återtar så länge Dimmeby inte har svarat.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "           39?DY",
        "*Åter B:Öv 12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB?39       1/1",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Återta begäran…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "DY",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Dimmeby ger klart med #. Tecknet blir > hos båda.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "           39>DY",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB>39          ",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Knastebo rapporterar faktisk avgång med #. Sträckan är upptagen (▶) och Dimmeby kan ta emot direkt.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "           39▶DY",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB▶39          ",
        "#In B:Sp   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "DY",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Dimmeby tar emot på planerat spår med #. Knastebo får beskedet 39 MOTTAGET med mottagarens kod.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "39 MOTTAGET     ",
        "DY         12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "39 ANK SP1      ",
        "KNB        12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Efter tre sekunder går Dimmeby tillbaka till översikten av sig själv.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "39 MOTTAGET     ",
        "DY         12:34"
       ],
       "changed": false
      },
      {
       "box": "DY",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": []
    },
    {
     "box": null,
     "keys": [],
     "wait": 2,
     "caption": "Fem sekunder efter ankomsten försvinner beskedet på Knastebo, utan kvittering. Sträckan är fri.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": []
    }
   ]
  },
  {
   "id": "annat-spar",
   "title": "Ta emot på ett annat spår",
   "mode": "Med klartecken",
   "intro": "När tåget ska in på ett annat spår än det planerade.",
   "setup": "39 har fått klart och avgått från Knastebo mot Dimmeby.",
   "boxes": [
    {
     "id": "KNB",
     "code": "KNB",
     "label": "KNB",
     "station": "Knastebo"
    },
    {
     "id": "DY",
     "code": "DY",
     "label": "DY",
     "station": "Dimmeby"
    }
   ],
   "start": [
    {
     "box": "KNB",
     "lines": [
      "           39▶DY",
      "C/D A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "DY",
     "lines": [
      "KNB▶39          ",
      "#In B:Sp   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "DY",
     "keys": [
      "B"
     ],
     "wait": null,
     "caption": "B väljer annat ankomstspår. Boxen börjar på spår 1.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "           39▶DY",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "DY",
       "lines": [
        "39 SPÅR 1       ",
        "#In C/D:Sp 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Ankommit på valt spår"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående spår"
      ],
      [
       "D",
       "Nästa spår"
      ]
     ]
    },
    {
     "box": "DY",
     "keys": [
      "D"
     ],
     "wait": null,
     "caption": "C/D bläddrar bland stationens spår.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "           39▶DY",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "DY",
       "lines": [
        "39 SPÅR 2       ",
        "#In C/D:Sp 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Ankommit på valt spår"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående spår"
      ],
      [
       "D",
       "Nästa spår"
      ]
     ]
    },
    {
     "box": "DY",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# tar emot på spår 2. Ankomsten registreras på det spåret.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "39 MOTTAGET     ",
        "DY         12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "39 ANK SP2      ",
        "KNB        12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    }
   ]
  },
  {
   "id": "neka",
   "title": "Neka en förfrågan",
   "mode": "Med klartecken",
   "intro": "Mottagaren kan inte ta emot tåget just nu.",
   "setup": "Knastebo har begärt klartecken för 39.",
   "boxes": [
    {
     "id": "KNB",
     "code": "KNB",
     "label": "KNB",
     "station": "Knastebo"
    },
    {
     "id": "DY",
     "code": "DY",
     "label": "DY",
     "station": "Dimmeby"
    }
   ],
   "start": [
    {
     "box": "KNB",
     "lines": [
      "           39?DY",
      "*Åter B:Öv 12:34"
     ],
     "changed": true
    },
    {
     "box": "DY",
     "lines": [
      "KNB?39       1/1",
      "#Ja *Nej   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "DY",
     "keys": [
      "*"
     ],
     "wait": null,
     "caption": "* på förfrågan frågar först: NEKA 39? Inget är ändrat än.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "           39?DY",
        "*Åter B:Öv 12:34"
       ],
       "changed": false
      },
      {
       "box": "DY",
       "lines": [
        "NEKA 39?        ",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Bekräfta neka"
      ],
      [
       "*",
       "Tillbaka utan att neka"
      ],
      [
       "A",
       "Förfrågningskö (1 väntar)"
      ]
     ]
    },
    {
     "box": "DY",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# bekräftar. Båda boxarna visar 39 NEKAT med den andra stationen under, och sträckan är fri igen.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "39 NEKAT        ",
        "DY         12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "39 NEKAT        ",
        "KNB        12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Efter tre sekunder går båda tillbaka till översikten av sig själva. Inget besked behöver kvitteras. Knastebo kan begära igen senare.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": []
    }
   ]
  },
  {
   "id": "aterta-begaran",
   "title": "Återta en begäran",
   "mode": "Med klartecken",
   "intro": "Avsändaren ångrar sig innan mottagaren har svarat.",
   "setup": "Knastebo har begärt klartecken för 39.",
   "boxes": [
    {
     "id": "KNB",
     "code": "KNB",
     "label": "KNB",
     "station": "Knastebo"
    },
    {
     "id": "DY",
     "code": "DY",
     "label": "DY",
     "station": "Dimmeby"
    }
   ],
   "start": [
    {
     "box": "KNB",
     "lines": [
      "           39?DY",
      "*Åter B:Öv 12:34"
     ],
     "changed": true
    },
    {
     "box": "DY",
     "lines": [
      "KNB?39       1/1",
      "#Ja *Nej   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "KNB",
     "keys": [
      "*"
     ],
     "wait": null,
     "caption": "* frågar först: ÅTER 39? Förfrågan ligger kvar hos Dimmeby tills du bekräftar.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "ÅTER 39?        ",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB?39       1/1",
        "#Ja *Nej   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Bekräfta återtagning"
      ],
      [
       "*",
       "Behåll begäran eller klartecken"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# återtar. Båda boxarna visar 39 ÅTERTAGET, och förfrågan är borta ur Dimmebys kö.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "39 ÅTERTAGET    ",
        "DY         12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "39 ÅTERTAGET    ",
        "KNB        12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Efter tre sekunder går båda tillbaka till översikten av sig själva.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": []
    }
   ]
  },
  {
   "id": "aterta-klartecken",
   "title": "Återta ett klartecken före avgång",
   "mode": "Med klartecken",
   "intro": "Tåget har fått klart men ska inte gå ändå. Efter faktisk avgång går det inte att återta.",
   "setup": "Dimmeby har gett klart för 39.",
   "boxes": [
    {
     "id": "KNB",
     "code": "KNB",
     "label": "KNB",
     "station": "Knastebo"
    },
    {
     "id": "DY",
     "code": "DY",
     "label": "DY",
     "station": "Dimmeby"
    }
   ],
   "start": [
    {
     "box": "KNB",
     "lines": [
      "           39>DY",
      "#Avg *Åter 12:34"
     ],
     "changed": true
    },
    {
     "box": "DY",
     "lines": [
      "KNB>39          ",
      "C/D A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "KNB",
     "keys": [
      "*"
     ],
     "wait": null,
     "caption": "* frågar först: ÅTER 39? Klartecknet gäller tills du bekräftar.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "ÅTER 39?        ",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB>39          ",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Bekräfta återtagning"
      ],
      [
       "*",
       "Behåll begäran eller klartecken"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# återtar. Båda boxarna visar 39 ÅTERTAGET: Dimmeby ska inte ta emot ett tåg som aldrig gick.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "39 ÅTERTAGET    ",
        "DY         12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "39 ÅTERTAGET    ",
        "KNB        12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Efter tre sekunder går båda tillbaka till översikten och sträckan är fri.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": []
    }
   ]
  },
  {
   "id": "tva-forfragningar",
   "title": "Två förfrågningar samtidigt",
   "mode": "Med klartecken",
   "intro": "Knastebo får förfrågningar från båda hållen.",
   "setup": null,
   "boxes": [
    {
     "id": "SVM",
     "code": "SVM",
     "label": "SVM",
     "station": "Sölvmora"
    },
    {
     "id": "KNB",
     "code": "KNB",
     "label": "KNB",
     "station": "Knastebo"
    },
    {
     "id": "DY",
     "code": "DY",
     "label": "DY",
     "station": "Dimmeby"
    }
   ],
   "start": [
    {
     "box": "SVM",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "KNB",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "DY",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "SVM",
     "keys": [
      "9",
      "3",
      "#"
     ],
     "wait": null,
     "caption": "Sölvmora skriver 93 och trycker #: förfrågan går direkt. Knastebo står i översikten och visar den.",
     "screens": [
      {
       "box": "SVM",
       "lines": [
        "          93?KNB",
        "*Åter B:Öv 12:34"
       ],
       "changed": true
      },
      {
       "box": "KNB",
       "lines": [
        "SVM?93       1/1",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "*",
       "Återta begäran…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "DY",
     "keys": [
      "9",
      "4",
      "#"
     ],
     "wait": null,
     "caption": "Dimmeby begär 94 på samma sätt. Knastebo stannar på förfrågan den visar; räknaren blir 1/2.",
     "screens": [
      {
       "box": "SVM",
       "lines": [
        "          93?KNB",
        "*Åter B:Öv 12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "SVM?93       1/2",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB?94          ",
        "*Åter B:Öv 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Återta begäran…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "D"
     ],
     "wait": null,
     "caption": "D bläddrar till nästa förfrågan i kön, 2/2.",
     "screens": [
      {
       "box": "SVM",
       "lines": [
        "          93?KNB",
        "*Åter B:Öv 12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "2/2        94?DY",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB?94          ",
        "*Åter B:Öv 12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Ge klart"
      ],
      [
       "*",
       "Neka begäran…"
      ],
      [
       "A",
       "Förfrågningskö (2 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående förfrågan"
      ],
      [
       "D",
       "Nästa förfrågan"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# ger klart för just det visade tåget, 94. Boxen stannar på det tåget.",
     "screens": [
      {
       "box": "SVM",
       "lines": [
        "          93?KNB",
        "*Åter B:Öv 12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "           94<DY",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB<94          ",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (1 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "A"
     ],
     "wait": null,
     "caption": "A öppnar kön igen. Kvar är 93 från Sölvmora.",
     "screens": [
      {
       "box": "SVM",
       "lines": [
        "          93?KNB",
        "*Åter B:Öv 12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "SVM?93       1/1",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB<94          ",
        "#Avg *Åter 12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Ge klart"
      ],
      [
       "*",
       "Neka begäran…"
      ],
      [
       "A",
       "Förfrågningskö (1 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående förfrågan"
      ],
      [
       "D",
       "Nästa förfrågan"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# ger klart även för 93.",
     "screens": [
      {
       "box": "SVM",
       "lines": [
        "          93>KNB",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      },
      {
       "box": "KNB",
       "lines": [
        "SVM>93          ",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB<94          ",
        "#Avg *Åter 12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    }
   ]
  },
  {
   "id": "hitta-aktivt",
   "title": "Hitta ett tåg som har fått klart",
   "mode": "Med klartecken",
   "intro": "Klartecknet kommer medan du gör något annat. B visar alla tåg som pågår.",
   "setup": "Knastebo har begärt klartecken för 17 mot Sölvmora och 39 mot Dimmeby, och står i översikten.",
   "boxes": [
    {
     "id": "SVM",
     "code": "SVM",
     "label": "SVM",
     "station": "Sölvmora"
    },
    {
     "id": "KNB",
     "code": "KNB",
     "label": "KNB",
     "station": "Knastebo"
    },
    {
     "id": "DY",
     "code": "DY",
     "label": "DY",
     "station": "Dimmeby"
    }
   ],
   "start": [
    {
     "box": "SVM",
     "lines": [
      "1/1       17?KNB",
      "#Ja *Nej   12:34"
     ],
     "changed": true
    },
    {
     "box": "KNB",
     "lines": [
      "SVM?17     39?DY",
      "B:Akt2 C/D 12:34"
     ],
     "changed": true
    },
    {
     "box": "DY",
     "lines": [
      "KNB?39       1/1",
      "#Ja *Nej   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "SVM",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Sölvmora ger klart för 17.",
     "screens": [
      {
       "box": "SVM",
       "lines": [
        "          17<KNB",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "KNB",
       "lines": [
        "SVM<17     39?DY",
        "B:Akt2 C/D 12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB?39       1/1",
        "#Ja *Nej   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "DY",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Dimmeby ger klart för 39. Knastebos översikt visar båda och B:Akt2: två aktiva tåg.",
     "screens": [
      {
       "box": "SVM",
       "lines": [
        "          17<KNB",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "SVM<17     39>DY",
        "B:Akt2 C/D 12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB>39          ",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "B"
     ],
     "wait": null,
     "caption": "B öppnar de aktiva tågen. Klarerade avgångar kommer först; 1/2 visar vilket du ser. Det går också att skriva tågnumret direkt.",
     "screens": [
      {
       "box": "SVM",
       "lines": [
        "          17<KNB",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "SVM<17       1/2",
        "#Avg C/D   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB>39          ",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Rapportera avgång"
      ],
      [
       "*",
       "Återta klartecken…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående aktiva tåg"
      ],
      [
       "D",
       "Nästa aktiva tåg"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "D"
     ],
     "wait": null,
     "caption": "D går till nästa aktiva tåg, 39 mot Dimmeby.",
     "screens": [
      {
       "box": "SVM",
       "lines": [
        "          17<KNB",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "2/2        39>DY",
        "#Avg C/D   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB>39          ",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Rapportera avgång"
      ],
      [
       "*",
       "Återta klartecken…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående aktiva tåg"
      ],
      [
       "D",
       "Nästa aktiva tåg"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# rapporterar avgång för just det visade tåget. 17 väntar kvar i listan.",
     "screens": [
      {
       "box": "SVM",
       "lines": [
        "          17<KNB",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "2/2        39▶DY",
        "C/D B:Öv   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB▶39          ",
        "#In B:Sp   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående aktiva tåg"
      ],
      [
       "D",
       "Nästa aktiva tåg"
      ]
     ]
    }
   ]
  },
  {
   "id": "direkt",
   "title": "Direkttrafik utan klartecken",
   "mode": "Direkttrafik",
   "intro": "På en sträcka med direkttrafik reserverar avsändaren själv. Mottagaren får ingen förfrågan.",
   "setup": null,
   "boxes": [
    {
     "id": "KNB",
     "code": "KNB",
     "label": "KNB",
     "station": "Knastebo"
    },
    {
     "id": "DY",
     "code": "DY",
     "label": "DY",
     "station": "Dimmeby"
    }
   ],
   "start": [
    {
     "box": "KNB",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "DY",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "KNB",
     "keys": [
      "3",
      "9",
      "#"
     ],
     "wait": null,
     "caption": "Knastebo skriver 39 och trycker #. På direkttrafik reserverar det sträckan direkt (>). Dimmeby ser tåget som aktivt: B:Akt1.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "           39>DY",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB>39          ",
        "B:Akt1 C/D 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Rapportera avgång"
      ],
      [
       "*",
       "Återta klartecken…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# rapporterar avgång.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "           39▶DY",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB▶39          ",
        "B:Akt1 C/D 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "DY",
     "keys": [
      "B"
     ],
     "wait": null,
     "caption": "Dimmeby öppnar det aktiva tåget med B.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "           39▶DY",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "DY",
       "lines": [
        "KNB▶39       1/1",
        "#In B:Sp   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Rapportera ankomst"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Annat ankomstspår"
      ],
      [
       "C",
       "Föregående aktiva tåg"
      ],
      [
       "D",
       "Nästa aktiva tåg"
      ]
     ]
    },
    {
     "box": "DY",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# tar emot på planerat spår.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "39 MOTTAGET     ",
        "DY         12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "39 ANK SP1      ",
        "KNB        12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    }
   ]
  },
  {
   "id": "tidtabell",
   "title": "Bläddra i tidtabellen",
   "mode": "Med klartecken",
   "intro": "Välj tåg ur stationens tidtabell i stället för att skriva numret.",
   "setup": null,
   "boxes": [
    {
     "id": "KNB",
     "code": "KNB",
     "label": "KNB",
     "station": "Knastebo"
    }
   ],
   "start": [
    {
     "box": "KNB",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# från översikten öppnar stationens kommande tåg, med planerad tid.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "17 AVG     12:35",
        "#Välj A:Kö 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Välj tåg"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Visa ankomster"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "D"
     ],
     "wait": null,
     "caption": "C/D bläddrar.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "39 AVG     12:38",
        "#Välj A:Kö 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Välj tåg"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Visa ankomster"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "B"
     ],
     "wait": null,
     "caption": "B filtrerar, först på ankomster. Även en ankomst som ingen har skickat går att välja och flytta hit.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "93 ANK     12:40",
        "#Välj A:Kö 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Välj tåg"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Visa avgångar"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "B"
     ],
     "wait": null,
     "caption": "B igen visar bara avgångar. Ett tredje B visar alla tåg.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "17 AVG     12:35",
        "#Välj A:Kö 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Välj tåg"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Visa alla tåg"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# väljer tåget. Nu kan du begära klartecken för det.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "SVM-17          ",
        "#Beg A:Kö  12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Begär klartecken"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    }
   ]
  },
  {
   "id": "nej",
   "title": "När boxen säger nej",
   "mode": "Med klartecken",
   "intro": "Boxen säger varför ett nummer inte går att välja. Siffrorna skickas först när du trycker #.",
   "setup": null,
   "boxes": [
    {
     "id": "KNB",
     "code": "KNB",
     "label": "KNB",
     "station": "Knastebo"
    }
   ],
   "start": [
    {
     "box": "KNB",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "KNB",
     "keys": [
      "1",
      "2",
      "3",
      "#"
     ],
     "wait": null,
     "caption": "Ett nummer som inte går vid stationen ger INGET TÅG.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "INGET TÅG       ",
        "           12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Beskedet försvinner av sig självt efter tre sekunder; # eller * stänger det direkt.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": []
    },
    {
     "box": "KNB",
     "keys": [
      "4"
     ],
     "wait": null,
     "caption": "Har du börjat skriva ett fel nummer, suddar B sista siffran …",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "TÅG: 4____      ",
        "#Sök B:Del 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Sök tåg (begär direkt)"
      ],
      [
       "*",
       "Avbryt inmatning"
      ],
      [
       "A",
       "Förfrågningskö (avbryt inmatning)"
      ],
      [
       "B",
       "Sudda siffra"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "*"
     ],
     "wait": null,
     "caption": "… och * tömmer hela inmatningen. Inget har skickats till servern.",
     "screens": [
      {
       "box": "KNB",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Visa kommande tåg"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Aktiva tåg (0)"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    }
   ]
  },
  {
   "id": "genomgaende",
   "title": "Genomgående tåg",
   "mode": "Med klartecken",
   "intro": "Tåg 55 kommer in från Dimmeby och går vidare mot Sölvmora med samma nummer. Numret gäller det som är på gång: först ankomsten, sedan avgången.",
   "setup": null,
   "boxes": [
    {
     "id": "DY",
     "code": "DY",
     "label": "DY",
     "station": "Dimmeby"
    },
    {
     "id": "KNB",
     "code": "KNB",
     "label": "KNB",
     "station": "Knastebo"
    },
    {
     "id": "SVM",
     "code": "SVM",
     "label": "SVM",
     "station": "Sölvmora"
    }
   ],
   "start": [
    {
     "box": "DY",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "KNB",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "SVM",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "DY",
     "keys": [
      "5",
      "5",
      "#"
     ],
     "wait": null,
     "caption": "Dimmeby begär 55 mot Knastebo; förfrågan går direkt.",
     "screens": [
      {
       "box": "DY",
       "lines": [
        "KNB?55          ",
        "*Åter B:Öv 12:34"
       ],
       "changed": true
      },
      {
       "box": "KNB",
       "lines": [
        "1/1        55?DY",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      },
      {
       "box": "SVM",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "*",
       "Återta begäran…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Knastebo står i översikten och ger klart.",
     "screens": [
      {
       "box": "DY",
       "lines": [
        "KNB<55          ",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      },
      {
       "box": "KNB",
       "lines": [
        "           55<DY",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "SVM",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "DY",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Dimmeby rapporterar avgång. Knastebo kan ta emot direkt.",
     "screens": [
      {
       "box": "DY",
       "lines": [
        "KNB◀55          ",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "KNB",
       "lines": [
        "           55◀DY",
        "#In B:Sp   12:34"
       ],
       "changed": true
      },
      {
       "box": "SVM",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Knastebo tar emot 55 på planerat spår.",
     "screens": [
      {
       "box": "DY",
       "lines": [
        "55 MOTTAGET     ",
        "KNB        12:34"
       ],
       "changed": true
      },
      {
       "box": "KNB",
       "lines": [
        "55 ANK SP2      ",
        "DY         12:34"
       ],
       "changed": true
      },
      {
       "box": "SVM",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Efter tre sekunder går Knastebo tillbaka till översikten.",
     "screens": [
      {
       "box": "DY",
       "lines": [
        "55 MOTTAGET     ",
        "KNB        12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "SVM",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": []
    },
    {
     "box": "KNB",
     "keys": [
      "5",
      "5",
      "#"
     ],
     "wait": null,
     "caption": "Nu gäller numret avgången mot Sölvmora, och förfrågan går direkt.",
     "screens": [
      {
       "box": "DY",
       "lines": [
        "55 MOTTAGET     ",
        "KNB        12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "SVM?55          ",
        "*Åter B:Öv 12:34"
       ],
       "changed": true
      },
      {
       "box": "SVM",
       "lines": [
        "1/1       55?KNB",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Återta begäran…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "SVM",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Sölvmora ger klart.",
     "screens": [
      {
       "box": "DY",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "KNB",
       "lines": [
        "SVM<55          ",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      },
      {
       "box": "SVM",
       "lines": [
        "          55<KNB",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Knastebo rapporterar avgång. Sölvmora kan ta emot.",
     "screens": [
      {
       "box": "DY",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "SVM◀55          ",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "SVM",
       "lines": [
        "          55◀KNB",
        "#In B:Sp   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    }
   ]
  },
  {
   "id": "flytta-genomgaende",
   "title": "Genomgående tåg som ingen skickat",
   "mode": "Med klartecken",
   "intro": "Dimmeby tappade bort 55 och skickade det aldrig, men tåget står i Knastebo. I systemet står det kvar i Dimmeby, så Knastebo flyttar det hit först och skickar det sedan vidare som vanligt (Benny #170).",
   "setup": null,
   "boxes": [
    {
     "id": "DY",
     "code": "DY",
     "label": "DY",
     "station": "Dimmeby"
    },
    {
     "id": "KNB",
     "code": "KNB",
     "label": "KNB",
     "station": "Knastebo"
    },
    {
     "id": "SVM",
     "code": "SVM",
     "label": "SVM",
     "station": "Sölvmora"
    }
   ],
   "start": [
    {
     "box": "DY",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "KNB",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "SVM",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "KNB",
     "keys": [
      "5",
      "5",
      "#"
     ],
     "wait": null,
     "caption": "Knastebo skriver 55. Tåget har inte kommit hit i systemet, så boxen frågar FLYTTA 55 HIT? och begär ingenting av Sölvmora.",
     "screens": [
      {
       "box": "DY",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "FLYTTA 55 HIT?  ",
        "#Ja B:Sp   12:34"
       ],
       "changed": true
      },
      {
       "box": "SVM",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Flytta hit"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Annat ankomstspår"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# flyttar 55 hit på planerat spår. Dimmebys del räknas som gjord: Dimmeby får beskedet 55 MOTTAGET och har inte längre 55 att skicka.",
     "screens": [
      {
       "box": "DY",
       "lines": [
        "55 MOTTAGET     ",
        "KNB        12:34"
       ],
       "changed": true
      },
      {
       "box": "KNB",
       "lines": [
        "55 ANK SP2      ",
        "DY         12:34"
       ],
       "changed": true
      },
      {
       "box": "SVM",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Efter tre sekunder går Knastebo tillbaka till översikten.",
     "screens": [
      {
       "box": "DY",
       "lines": [
        "55 MOTTAGET     ",
        "KNB        12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "SVM",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": []
    },
    {
     "box": "KNB",
     "keys": [
      "5",
      "5",
      "#"
     ],
     "wait": null,
     "caption": "Nu står 55 här, och numret gäller avgången mot Sölvmora. Förfrågan går direkt.",
     "screens": [
      {
       "box": "DY",
       "lines": [
        "55 MOTTAGET     ",
        "KNB        12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "SVM?55          ",
        "*Åter B:Öv 12:34"
       ],
       "changed": true
      },
      {
       "box": "SVM",
       "lines": [
        "1/1       55?KNB",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Återta begäran…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "SVM",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Sölvmora ger klart.",
     "screens": [
      {
       "box": "DY",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "KNB",
       "lines": [
        "SVM<55          ",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      },
      {
       "box": "SVM",
       "lines": [
        "          55<KNB",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Knastebo rapporterar avgång. Sölvmora kan ta emot.",
     "screens": [
      {
       "box": "DY",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "SVM◀55          ",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "SVM",
       "lines": [
        "          55◀KNB",
        "#In B:Sp   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    }
   ]
  },
  {
   "id": "placera",
   "title": "Flytta hit ett tåg som ingen skickat",
   "mode": "Med klartecken",
   "intro": "Sölvmora skickade aldrig 93, men tåget kom till Knastebo. Knastebo flyttar det hit i efterhand, med tidtabellens spår som förslag, och spelet går vidare.",
   "setup": null,
   "boxes": [
    {
     "id": "SVM",
     "code": "SVM",
     "label": "SVM",
     "station": "Sölvmora"
    },
    {
     "id": "KNB",
     "code": "KNB",
     "label": "KNB",
     "station": "Knastebo"
    }
   ],
   "start": [
    {
     "box": "SVM",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "KNB",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "KNB",
     "keys": [
      "9",
      "3",
      "#"
     ],
     "wait": null,
     "caption": "Knastebo skriver 93. Boxen frågar FLYTTA 93 HIT?: # flyttar det till planerat spår.",
     "screens": [
      {
       "box": "SVM",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "FLYTTA 93 HIT?  ",
        "#Ja B:Sp   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Flytta hit"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Annat ankomstspår"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "B"
     ],
     "wait": null,
     "caption": "B väljer ett annat spår i stället. Boxen börjar på spår 1.",
     "screens": [
      {
       "box": "SVM",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "93 SPÅR 1       ",
        "#In C/D:Sp 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Ankommit på valt spår"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående spår"
      ],
      [
       "D",
       "Nästa spår"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "D"
     ],
     "wait": null,
     "caption": "C/D bläddrar bland stationens spår.",
     "screens": [
      {
       "box": "SVM",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB",
       "lines": [
        "93 SPÅR 2       ",
        "#In C/D:Sp 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Ankommit på valt spår"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående spår"
      ],
      [
       "D",
       "Nästa spår"
      ]
     ]
    },
    {
     "box": "KNB",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# flyttar 93 hit, på det valda spåret. Sölvmoras del räknas som gjord.",
     "screens": [
      {
       "box": "SVM",
       "lines": [
        "93 MOTTAGET     ",
        "KNB        12:34"
       ],
       "changed": true
      },
      {
       "box": "KNB",
       "lines": [
        "93 ANK SP2      ",
        "SVM        12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    }
   ]
  },
  {
   "id": "tva-boxar",
   "title": "Två boxar på samma station",
   "mode": "Med klartecken",
   "intro": "En station kan ha en box per sida. Varje box hanterar bara tågen på sina sträckor.",
   "setup": null,
   "boxes": [
    {
     "id": "KNB-V",
     "code": "KNB",
     "label": "KNB · vänster",
     "station": "Knastebo"
    },
    {
     "id": "KNB-H",
     "code": "KNB",
     "label": "KNB · höger",
     "station": "Knastebo"
    },
    {
     "id": "DY",
     "code": "DY",
     "label": "DY",
     "station": "Dimmeby"
    }
   ],
   "start": [
    {
     "box": "KNB-V",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "KNB-H",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "DY",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "KNB-V",
     "keys": [
      "3",
      "9",
      "#"
     ],
     "wait": null,
     "caption": "Vänsterboxen (mot Sölvmora) söker 39, som går mot Dimmeby. Svaret blir ANNAN SIDA.",
     "screens": [
      {
       "box": "KNB-V",
       "lines": [
        "ANNAN SIDA      ",
        "           12:34"
       ],
       "changed": true
      },
      {
       "box": "KNB-H",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "DY",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Beskedet försvinner av sig självt efter tre sekunder.",
     "screens": [
      {
       "box": "KNB-V",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "KNB-H",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "DY",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": []
    },
    {
     "box": "KNB-H",
     "keys": [
      "3",
      "9",
      "#"
     ],
     "wait": null,
     "caption": "Högerboxen hittar tåget och begär klartecken direkt.",
     "screens": [
      {
       "box": "KNB-V",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB-H",
       "lines": [
        "           39?DY",
        "*Åter B:Öv 12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB?39       1/1",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Återta begäran…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "DY",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Dimmeby ger klart. På Knastebo visar bara högerboxen tåget.",
     "screens": [
      {
       "box": "KNB-V",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "KNB-H",
       "lines": [
        "           39>DY",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      },
      {
       "box": "DY",
       "lines": [
        "KNB>39          ",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    }
   ]
  }
 ]
};
