// Generated by scripts/tmbox_flows.py from the server-16x2 engine; do not edit.
// tests/test_tmbox_flows.py fails when the engine and this file disagree.
globalThis.TMBoxFlows = {
 "profile": "server-16x2",
 "clock": "12:34",
 "stations": [
  {
   "code": "MUN",
   "name": "Munkeröd"
  },
  {
   "code": "CDA",
   "name": "Charlottendal"
  },
  {
   "code": "VA",
   "name": "Vagnsta"
  }
 ],
 "flows": [
  {
   "id": "klarera",
   "title": "Klartecken, avgång och ankomst",
   "mode": "Med klartecken",
   "intro": "Det vanliga flödet på en sträcka med klartecken: avsändaren begär, mottagaren ger klart, avsändaren rapporterar avgång och mottagaren tar emot.",
   "setup": null,
   "boxes": [
    {
     "id": "CDA",
     "code": "CDA",
     "label": "CDA",
     "station": "Charlottendal"
    },
    {
     "id": "VA",
     "code": "VA",
     "label": "VA",
     "station": "Vagnsta"
    }
   ],
   "start": [
    {
     "box": "CDA",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "VA",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "CDA",
     "keys": [
      "3",
      "9"
     ],
     "wait": null,
     "caption": "Skriv tågnumret direkt från översikten. Siffrorna stannar i boxen tills du trycker #.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "TÅG: 39___      ",
        "#Sök B:Del 12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Sök tåg (begär direkt)"
      ],
      [
       "*",
       "Avbryt inmatning"
      ],
      [
       "A",
       "Förfrågningskö (avbryt inmatning)"
      ],
      [
       "B",
       "Sudda siffra"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# söker tåget och begär klartecken (?) i samma tryck. 39 ska till Vagnsta, som står i översikten och visar förfrågan direkt. * återtar så länge Vagnsta inte har svarat.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "           39?VA",
        "*Åter B:Öv 12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA?39       1/1",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Återta begäran…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "VA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Vagnsta ger klart med #. Tecknet blir > hos båda.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "           39>VA",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA>39          ",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Charlottendal rapporterar faktisk avgång med #. Sträckan är upptagen (▶) och Vagnsta kan ta emot direkt.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "           39▶VA",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA▶39          ",
        "#In B:Sp   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "VA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Vagnsta tar emot på planerat spår med #. Charlottendal får beskedet 39 MOTTAGET med mottagarens kod.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "39 MOTTAGET     ",
        "VA         12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "39 ANK SP1      ",
        "CDA        12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Efter tre sekunder går Vagnsta tillbaka till översikten av sig själv.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "39 MOTTAGET     ",
        "VA         12:34"
       ],
       "changed": false
      },
      {
       "box": "VA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": []
    },
    {
     "box": null,
     "keys": [],
     "wait": 2,
     "caption": "Fem sekunder efter ankomsten försvinner beskedet på Charlottendal, utan kvittering. Sträckan är fri.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": []
    }
   ]
  },
  {
   "id": "annat-spar",
   "title": "Ta emot på ett annat spår",
   "mode": "Med klartecken",
   "intro": "När tåget ska in på ett annat spår än det planerade.",
   "setup": "39 har fått klart och avgått från Charlottendal mot Vagnsta.",
   "boxes": [
    {
     "id": "CDA",
     "code": "CDA",
     "label": "CDA",
     "station": "Charlottendal"
    },
    {
     "id": "VA",
     "code": "VA",
     "label": "VA",
     "station": "Vagnsta"
    }
   ],
   "start": [
    {
     "box": "CDA",
     "lines": [
      "           39▶VA",
      "C/D A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "VA",
     "lines": [
      "CDA▶39          ",
      "#In B:Sp   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "VA",
     "keys": [
      "B"
     ],
     "wait": null,
     "caption": "B väljer annat ankomstspår. Boxen börjar på spår 1.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "           39▶VA",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "VA",
       "lines": [
        "39 SPÅR 1       ",
        "#In C/D:Sp 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Ankommit på valt spår"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående spår"
      ],
      [
       "D",
       "Nästa spår"
      ]
     ]
    },
    {
     "box": "VA",
     "keys": [
      "D"
     ],
     "wait": null,
     "caption": "C/D bläddrar bland stationens spår.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "           39▶VA",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "VA",
       "lines": [
        "39 SPÅR 2       ",
        "#In C/D:Sp 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Ankommit på valt spår"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående spår"
      ],
      [
       "D",
       "Nästa spår"
      ]
     ]
    },
    {
     "box": "VA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# tar emot på spår 2. Ankomsten registreras på det spåret.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "39 MOTTAGET     ",
        "VA         12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "39 ANK SP2      ",
        "CDA        12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    }
   ]
  },
  {
   "id": "neka",
   "title": "Neka en förfrågan",
   "mode": "Med klartecken",
   "intro": "Mottagaren kan inte ta emot tåget just nu.",
   "setup": "Charlottendal har begärt klartecken för 39.",
   "boxes": [
    {
     "id": "CDA",
     "code": "CDA",
     "label": "CDA",
     "station": "Charlottendal"
    },
    {
     "id": "VA",
     "code": "VA",
     "label": "VA",
     "station": "Vagnsta"
    }
   ],
   "start": [
    {
     "box": "CDA",
     "lines": [
      "           39?VA",
      "*Åter B:Öv 12:34"
     ],
     "changed": true
    },
    {
     "box": "VA",
     "lines": [
      "CDA?39       1/1",
      "#Ja *Nej   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "VA",
     "keys": [
      "*"
     ],
     "wait": null,
     "caption": "* på förfrågan frågar först: NEKA 39? Inget är ändrat än.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "           39?VA",
        "*Åter B:Öv 12:34"
       ],
       "changed": false
      },
      {
       "box": "VA",
       "lines": [
        "NEKA 39?        ",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Bekräfta neka"
      ],
      [
       "*",
       "Tillbaka utan att neka"
      ],
      [
       "A",
       "Förfrågningskö (1 väntar)"
      ]
     ]
    },
    {
     "box": "VA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# bekräftar. Båda boxarna visar 39 NEKAT med den andra stationen under, och sträckan är fri igen.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "39 NEKAT        ",
        "VA         12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "39 NEKAT        ",
        "CDA        12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Efter tre sekunder går båda tillbaka till översikten av sig själva. Inget besked behöver kvitteras. Charlottendal kan begära igen senare.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": []
    }
   ]
  },
  {
   "id": "aterta-begaran",
   "title": "Återta en begäran",
   "mode": "Med klartecken",
   "intro": "Avsändaren ångrar sig innan mottagaren har svarat.",
   "setup": "Charlottendal har begärt klartecken för 39.",
   "boxes": [
    {
     "id": "CDA",
     "code": "CDA",
     "label": "CDA",
     "station": "Charlottendal"
    },
    {
     "id": "VA",
     "code": "VA",
     "label": "VA",
     "station": "Vagnsta"
    }
   ],
   "start": [
    {
     "box": "CDA",
     "lines": [
      "           39?VA",
      "*Åter B:Öv 12:34"
     ],
     "changed": true
    },
    {
     "box": "VA",
     "lines": [
      "CDA?39       1/1",
      "#Ja *Nej   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "CDA",
     "keys": [
      "*"
     ],
     "wait": null,
     "caption": "* frågar först: ÅTER 39? Förfrågan ligger kvar hos Vagnsta tills du bekräftar.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "ÅTER 39?        ",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA?39       1/1",
        "#Ja *Nej   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Bekräfta återtagning"
      ],
      [
       "*",
       "Behåll begäran eller klartecken"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# återtar. Båda boxarna visar 39 ÅTERTAGET, och förfrågan är borta ur Vagnstas kö.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "39 ÅTERTAGET    ",
        "VA         12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "39 ÅTERTAGET    ",
        "CDA        12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Efter tre sekunder går båda tillbaka till översikten av sig själva.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": []
    }
   ]
  },
  {
   "id": "aterta-klartecken",
   "title": "Återta ett klartecken före avgång",
   "mode": "Med klartecken",
   "intro": "Tåget har fått klart men ska inte gå ändå. Efter faktisk avgång går det inte att återta.",
   "setup": "Vagnsta har gett klart för 39.",
   "boxes": [
    {
     "id": "CDA",
     "code": "CDA",
     "label": "CDA",
     "station": "Charlottendal"
    },
    {
     "id": "VA",
     "code": "VA",
     "label": "VA",
     "station": "Vagnsta"
    }
   ],
   "start": [
    {
     "box": "CDA",
     "lines": [
      "           39>VA",
      "#Avg *Åter 12:34"
     ],
     "changed": true
    },
    {
     "box": "VA",
     "lines": [
      "CDA>39          ",
      "C/D A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "CDA",
     "keys": [
      "*"
     ],
     "wait": null,
     "caption": "* frågar först: ÅTER 39? Klartecknet gäller tills du bekräftar.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "ÅTER 39?        ",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA>39          ",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Bekräfta återtagning"
      ],
      [
       "*",
       "Behåll begäran eller klartecken"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# återtar. Båda boxarna visar 39 ÅTERTAGET: Vagnsta ska inte ta emot ett tåg som aldrig gick.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "39 ÅTERTAGET    ",
        "VA         12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "39 ÅTERTAGET    ",
        "CDA        12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Efter tre sekunder går båda tillbaka till översikten och sträckan är fri.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": []
    }
   ]
  },
  {
   "id": "tva-forfragningar",
   "title": "Två förfrågningar samtidigt",
   "mode": "Med klartecken",
   "intro": "Charlottendal får förfrågningar från båda hållen.",
   "setup": null,
   "boxes": [
    {
     "id": "MUN",
     "code": "MUN",
     "label": "MUN",
     "station": "Munkeröd"
    },
    {
     "id": "CDA",
     "code": "CDA",
     "label": "CDA",
     "station": "Charlottendal"
    },
    {
     "id": "VA",
     "code": "VA",
     "label": "VA",
     "station": "Vagnsta"
    }
   ],
   "start": [
    {
     "box": "MUN",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "CDA",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "VA",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "MUN",
     "keys": [
      "9",
      "3",
      "#"
     ],
     "wait": null,
     "caption": "Munkeröd skriver 93 och trycker #: förfrågan går direkt. Charlottendal står i översikten och visar den.",
     "screens": [
      {
       "box": "MUN",
       "lines": [
        "          93?CDA",
        "*Åter B:Öv 12:34"
       ],
       "changed": true
      },
      {
       "box": "CDA",
       "lines": [
        "MUN?93       1/1",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "*",
       "Återta begäran…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "VA",
     "keys": [
      "9",
      "4",
      "#"
     ],
     "wait": null,
     "caption": "Vagnsta begär 94 på samma sätt. Charlottendal stannar på förfrågan den visar; räknaren blir 1/2.",
     "screens": [
      {
       "box": "MUN",
       "lines": [
        "          93?CDA",
        "*Åter B:Öv 12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "MUN?93       1/2",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA?94          ",
        "*Åter B:Öv 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Återta begäran…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "D"
     ],
     "wait": null,
     "caption": "D bläddrar till nästa förfrågan i kön, 2/2.",
     "screens": [
      {
       "box": "MUN",
       "lines": [
        "          93?CDA",
        "*Åter B:Öv 12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "2/2        94?VA",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA?94          ",
        "*Åter B:Öv 12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Ge klart"
      ],
      [
       "*",
       "Neka begäran…"
      ],
      [
       "A",
       "Förfrågningskö (2 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående förfrågan"
      ],
      [
       "D",
       "Nästa förfrågan"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# ger klart för just det visade tåget, 94. Boxen stannar på det tåget.",
     "screens": [
      {
       "box": "MUN",
       "lines": [
        "          93?CDA",
        "*Åter B:Öv 12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "           94<VA",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA<94          ",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (1 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "A"
     ],
     "wait": null,
     "caption": "A öppnar kön igen. Kvar är 93 från Munkeröd.",
     "screens": [
      {
       "box": "MUN",
       "lines": [
        "          93?CDA",
        "*Åter B:Öv 12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "MUN?93       1/1",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA<94          ",
        "#Avg *Åter 12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Ge klart"
      ],
      [
       "*",
       "Neka begäran…"
      ],
      [
       "A",
       "Förfrågningskö (1 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående förfrågan"
      ],
      [
       "D",
       "Nästa förfrågan"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# ger klart även för 93.",
     "screens": [
      {
       "box": "MUN",
       "lines": [
        "          93>CDA",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      },
      {
       "box": "CDA",
       "lines": [
        "MUN>93          ",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA<94          ",
        "#Avg *Åter 12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    }
   ]
  },
  {
   "id": "hitta-aktivt",
   "title": "Hitta ett tåg som har fått klart",
   "mode": "Med klartecken",
   "intro": "Klartecknet kommer medan du gör något annat. B visar alla tåg som pågår.",
   "setup": "Charlottendal har begärt klartecken för 17 mot Munkeröd och 39 mot Vagnsta, och står i översikten.",
   "boxes": [
    {
     "id": "MUN",
     "code": "MUN",
     "label": "MUN",
     "station": "Munkeröd"
    },
    {
     "id": "CDA",
     "code": "CDA",
     "label": "CDA",
     "station": "Charlottendal"
    },
    {
     "id": "VA",
     "code": "VA",
     "label": "VA",
     "station": "Vagnsta"
    }
   ],
   "start": [
    {
     "box": "MUN",
     "lines": [
      "1/1       17?CDA",
      "#Ja *Nej   12:34"
     ],
     "changed": true
    },
    {
     "box": "CDA",
     "lines": [
      "MUN?17     39?VA",
      "B:Akt2 C/D 12:34"
     ],
     "changed": true
    },
    {
     "box": "VA",
     "lines": [
      "CDA?39       1/1",
      "#Ja *Nej   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "MUN",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Munkeröd ger klart för 17.",
     "screens": [
      {
       "box": "MUN",
       "lines": [
        "          17<CDA",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "CDA",
       "lines": [
        "MUN<17     39?VA",
        "B:Akt2 C/D 12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA?39       1/1",
        "#Ja *Nej   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "VA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Vagnsta ger klart för 39. Charlottendals översikt visar båda och B:Akt2: två aktiva tåg.",
     "screens": [
      {
       "box": "MUN",
       "lines": [
        "          17<CDA",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "MUN<17     39>VA",
        "B:Akt2 C/D 12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA>39          ",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "B"
     ],
     "wait": null,
     "caption": "B öppnar de aktiva tågen. Klarerade avgångar kommer först; 1/2 visar vilket du ser. Det går också att skriva tågnumret direkt.",
     "screens": [
      {
       "box": "MUN",
       "lines": [
        "          17<CDA",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "MUN<17       1/2",
        "#Avg C/D   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA>39          ",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Rapportera avgång"
      ],
      [
       "*",
       "Återta klartecken…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående aktiva tåg"
      ],
      [
       "D",
       "Nästa aktiva tåg"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "D"
     ],
     "wait": null,
     "caption": "D går till nästa aktiva tåg, 39 mot Vagnsta.",
     "screens": [
      {
       "box": "MUN",
       "lines": [
        "          17<CDA",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "2/2        39>VA",
        "#Avg C/D   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA>39          ",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Rapportera avgång"
      ],
      [
       "*",
       "Återta klartecken…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående aktiva tåg"
      ],
      [
       "D",
       "Nästa aktiva tåg"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# rapporterar avgång för just det visade tåget. 17 väntar kvar i listan.",
     "screens": [
      {
       "box": "MUN",
       "lines": [
        "          17<CDA",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "2/2        39▶VA",
        "C/D B:Öv   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA▶39          ",
        "#In B:Sp   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående aktiva tåg"
      ],
      [
       "D",
       "Nästa aktiva tåg"
      ]
     ]
    }
   ]
  },
  {
   "id": "direkt",
   "title": "Direkttrafik utan klartecken",
   "mode": "Direkttrafik",
   "intro": "På en sträcka med direkttrafik reserverar avsändaren själv. Mottagaren får ingen förfrågan.",
   "setup": null,
   "boxes": [
    {
     "id": "CDA",
     "code": "CDA",
     "label": "CDA",
     "station": "Charlottendal"
    },
    {
     "id": "VA",
     "code": "VA",
     "label": "VA",
     "station": "Vagnsta"
    }
   ],
   "start": [
    {
     "box": "CDA",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "VA",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "CDA",
     "keys": [
      "3",
      "9",
      "#"
     ],
     "wait": null,
     "caption": "Charlottendal skriver 39 och trycker #. På direkttrafik reserverar det sträckan direkt (>). Vagnsta ser tåget som aktivt: B:Akt1.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "           39>VA",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA>39          ",
        "B:Akt1 C/D 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Rapportera avgång"
      ],
      [
       "*",
       "Återta klartecken…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# rapporterar avgång.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "           39▶VA",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA▶39          ",
        "B:Akt1 C/D 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "VA",
     "keys": [
      "B"
     ],
     "wait": null,
     "caption": "Vagnsta öppnar det aktiva tåget med B.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "           39▶VA",
        "C/D A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "VA",
       "lines": [
        "CDA▶39       1/1",
        "#In B:Sp   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Rapportera ankomst"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Annat ankomstspår"
      ],
      [
       "C",
       "Föregående aktiva tåg"
      ],
      [
       "D",
       "Nästa aktiva tåg"
      ]
     ]
    },
    {
     "box": "VA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# tar emot på planerat spår.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "39 MOTTAGET     ",
        "VA         12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "39 ANK SP1      ",
        "CDA        12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    }
   ]
  },
  {
   "id": "tidtabell",
   "title": "Bläddra i tidtabellen",
   "mode": "Med klartecken",
   "intro": "Välj tåg ur stationens tidtabell i stället för att skriva numret.",
   "setup": null,
   "boxes": [
    {
     "id": "CDA",
     "code": "CDA",
     "label": "CDA",
     "station": "Charlottendal"
    }
   ],
   "start": [
    {
     "box": "CDA",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# från översikten öppnar stationens kommande tåg, med planerad tid.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "17 AVG     12:35",
        "#Välj A:Kö 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Välj tåg"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Visa ankomster"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "D"
     ],
     "wait": null,
     "caption": "C/D bläddrar.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "39 AVG     12:38",
        "#Välj A:Kö 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Välj tåg"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Visa ankomster"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "B"
     ],
     "wait": null,
     "caption": "B filtrerar, först på ankomster. Även en ankomst som ingen har skickat går att välja och flytta hit.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "93 ANK     12:40",
        "#Välj A:Kö 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Välj tåg"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Visa avgångar"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "B"
     ],
     "wait": null,
     "caption": "B igen visar bara avgångar. Ett tredje B visar alla tåg.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "17 AVG     12:35",
        "#Välj A:Kö 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Välj tåg"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Visa alla tåg"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# väljer tåget. Nu kan du begära klartecken för det.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "MUN-17          ",
        "#Beg A:Kö  12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Begär klartecken"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    }
   ]
  },
  {
   "id": "nej",
   "title": "När boxen säger nej",
   "mode": "Med klartecken",
   "intro": "Boxen säger varför ett nummer inte går att välja. Siffrorna skickas först när du trycker #.",
   "setup": null,
   "boxes": [
    {
     "id": "CDA",
     "code": "CDA",
     "label": "CDA",
     "station": "Charlottendal"
    }
   ],
   "start": [
    {
     "box": "CDA",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "CDA",
     "keys": [
      "1",
      "2",
      "3",
      "#"
     ],
     "wait": null,
     "caption": "Ett nummer som inte går vid stationen ger INGET TÅG.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "INGET TÅG       ",
        "           12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Beskedet försvinner av sig självt efter tre sekunder; # eller * stänger det direkt.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": []
    },
    {
     "box": "CDA",
     "keys": [
      "4"
     ],
     "wait": null,
     "caption": "Har du börjat skriva ett fel nummer, suddar B sista siffran …",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "TÅG: 4____      ",
        "#Sök B:Del 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Sök tåg (begär direkt)"
      ],
      [
       "*",
       "Avbryt inmatning"
      ],
      [
       "A",
       "Förfrågningskö (avbryt inmatning)"
      ],
      [
       "B",
       "Sudda siffra"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "*"
     ],
     "wait": null,
     "caption": "… och * tömmer hela inmatningen. Inget har skickats till servern.",
     "screens": [
      {
       "box": "CDA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Visa kommande tåg"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Aktiva tåg (0)"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    }
   ]
  },
  {
   "id": "genomgaende",
   "title": "Genomgående tåg",
   "mode": "Med klartecken",
   "intro": "Tåg 55 kommer in från Vagnsta och går vidare mot Munkeröd med samma nummer. Numret gäller det som är på gång: först ankomsten, sedan avgången.",
   "setup": null,
   "boxes": [
    {
     "id": "VA",
     "code": "VA",
     "label": "VA",
     "station": "Vagnsta"
    },
    {
     "id": "CDA",
     "code": "CDA",
     "label": "CDA",
     "station": "Charlottendal"
    },
    {
     "id": "MUN",
     "code": "MUN",
     "label": "MUN",
     "station": "Munkeröd"
    }
   ],
   "start": [
    {
     "box": "VA",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "CDA",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "MUN",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "VA",
     "keys": [
      "5",
      "5",
      "#"
     ],
     "wait": null,
     "caption": "Vagnsta begär 55 mot Charlottendal; förfrågan går direkt.",
     "screens": [
      {
       "box": "VA",
       "lines": [
        "CDA?55          ",
        "*Åter B:Öv 12:34"
       ],
       "changed": true
      },
      {
       "box": "CDA",
       "lines": [
        "1/1        55?VA",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      },
      {
       "box": "MUN",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "*",
       "Återta begäran…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Charlottendal står i översikten och ger klart.",
     "screens": [
      {
       "box": "VA",
       "lines": [
        "CDA<55          ",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      },
      {
       "box": "CDA",
       "lines": [
        "           55<VA",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "MUN",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "VA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Vagnsta rapporterar avgång. Charlottendal kan ta emot direkt.",
     "screens": [
      {
       "box": "VA",
       "lines": [
        "CDA◀55          ",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "CDA",
       "lines": [
        "           55◀VA",
        "#In B:Sp   12:34"
       ],
       "changed": true
      },
      {
       "box": "MUN",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Charlottendal tar emot 55 på planerat spår.",
     "screens": [
      {
       "box": "VA",
       "lines": [
        "55 MOTTAGET     ",
        "CDA        12:34"
       ],
       "changed": true
      },
      {
       "box": "CDA",
       "lines": [
        "55 ANK SP2      ",
        "VA         12:34"
       ],
       "changed": true
      },
      {
       "box": "MUN",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Efter tre sekunder går Charlottendal tillbaka till översikten.",
     "screens": [
      {
       "box": "VA",
       "lines": [
        "55 MOTTAGET     ",
        "CDA        12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "MUN",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": []
    },
    {
     "box": "CDA",
     "keys": [
      "5",
      "5",
      "#"
     ],
     "wait": null,
     "caption": "Nu gäller numret avgången mot Munkeröd, och förfrågan går direkt.",
     "screens": [
      {
       "box": "VA",
       "lines": [
        "55 MOTTAGET     ",
        "CDA        12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "MUN?55          ",
        "*Åter B:Öv 12:34"
       ],
       "changed": true
      },
      {
       "box": "MUN",
       "lines": [
        "1/1       55?CDA",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Återta begäran…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "MUN",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Munkeröd ger klart.",
     "screens": [
      {
       "box": "VA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "CDA",
       "lines": [
        "MUN<55          ",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      },
      {
       "box": "MUN",
       "lines": [
        "          55<CDA",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Charlottendal rapporterar avgång. Munkeröd kan ta emot.",
     "screens": [
      {
       "box": "VA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "MUN◀55          ",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "MUN",
       "lines": [
        "          55◀CDA",
        "#In B:Sp   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    }
   ]
  },
  {
   "id": "flytta-genomgaende",
   "title": "Genomgående tåg som ingen skickat",
   "mode": "Med klartecken",
   "intro": "Vagnsta tappade bort 55 och skickade det aldrig, men tåget står i Charlottendal. I systemet står det kvar i Vagnsta, så Charlottendal flyttar det hit först och skickar det sedan vidare som vanligt (Benny #170).",
   "setup": null,
   "boxes": [
    {
     "id": "VA",
     "code": "VA",
     "label": "VA",
     "station": "Vagnsta"
    },
    {
     "id": "CDA",
     "code": "CDA",
     "label": "CDA",
     "station": "Charlottendal"
    },
    {
     "id": "MUN",
     "code": "MUN",
     "label": "MUN",
     "station": "Munkeröd"
    }
   ],
   "start": [
    {
     "box": "VA",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "CDA",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "MUN",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "CDA",
     "keys": [
      "5",
      "5",
      "#"
     ],
     "wait": null,
     "caption": "Charlottendal skriver 55. Tåget har inte kommit hit i systemet, så boxen frågar FLYTTA 55 HIT? och begär ingenting av Munkeröd.",
     "screens": [
      {
       "box": "VA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "FLYTTA 55 HIT?  ",
        "#Ja B:Sp   12:34"
       ],
       "changed": true
      },
      {
       "box": "MUN",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "Flytta hit"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Annat ankomstspår"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# flyttar 55 hit på planerat spår. Vagnstas del räknas som gjord: Vagnsta får beskedet 55 MOTTAGET och har inte längre 55 att skicka.",
     "screens": [
      {
       "box": "VA",
       "lines": [
        "55 MOTTAGET     ",
        "CDA        12:34"
       ],
       "changed": true
      },
      {
       "box": "CDA",
       "lines": [
        "55 ANK SP2      ",
        "VA         12:34"
       ],
       "changed": true
      },
      {
       "box": "MUN",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Efter tre sekunder går Charlottendal tillbaka till översikten.",
     "screens": [
      {
       "box": "VA",
       "lines": [
        "55 MOTTAGET     ",
        "CDA        12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "MUN",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": []
    },
    {
     "box": "CDA",
     "keys": [
      "5",
      "5",
      "#"
     ],
     "wait": null,
     "caption": "Nu står 55 här, och numret gäller avgången mot Munkeröd. Förfrågan går direkt.",
     "screens": [
      {
       "box": "VA",
       "lines": [
        "55 MOTTAGET     ",
        "CDA        12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "MUN?55          ",
        "*Åter B:Öv 12:34"
       ],
       "changed": true
      },
      {
       "box": "MUN",
       "lines": [
        "1/1       55?CDA",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Återta begäran…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "MUN",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Munkeröd ger klart.",
     "screens": [
      {
       "box": "VA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "CDA",
       "lines": [
        "MUN<55          ",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      },
      {
       "box": "MUN",
       "lines": [
        "          55<CDA",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Charlottendal rapporterar avgång. Munkeröd kan ta emot.",
     "screens": [
      {
       "box": "VA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "MUN◀55          ",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "MUN",
       "lines": [
        "          55◀CDA",
        "#In B:Sp   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    }
   ]
  },
  {
   "id": "placera",
   "title": "Flytta hit ett tåg som ingen skickat",
   "mode": "Med klartecken",
   "intro": "Munkeröd skickade aldrig 93, men tåget kom till Charlottendal. Charlottendal flyttar det hit i efterhand, med tidtabellens spår som förslag, och spelet går vidare.",
   "setup": null,
   "boxes": [
    {
     "id": "MUN",
     "code": "MUN",
     "label": "MUN",
     "station": "Munkeröd"
    },
    {
     "id": "CDA",
     "code": "CDA",
     "label": "CDA",
     "station": "Charlottendal"
    }
   ],
   "start": [
    {
     "box": "MUN",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "CDA",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "CDA",
     "keys": [
      "9",
      "3",
      "#"
     ],
     "wait": null,
     "caption": "Charlottendal skriver 93. Boxen frågar FLYTTA 93 HIT?: # flyttar det till planerat spår.",
     "screens": [
      {
       "box": "MUN",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "FLYTTA 93 HIT?  ",
        "#Ja B:Sp   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Flytta hit"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Annat ankomstspår"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "B"
     ],
     "wait": null,
     "caption": "B väljer ett annat spår i stället. Boxen börjar på spår 1.",
     "screens": [
      {
       "box": "MUN",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "93 SPÅR 1       ",
        "#In C/D:Sp 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Ankommit på valt spår"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående spår"
      ],
      [
       "D",
       "Nästa spår"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "D"
     ],
     "wait": null,
     "caption": "C/D bläddrar bland stationens spår.",
     "screens": [
      {
       "box": "MUN",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA",
       "lines": [
        "93 SPÅR 2       ",
        "#In C/D:Sp 12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "Ankommit på valt spår"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "C",
       "Föregående spår"
      ],
      [
       "D",
       "Nästa spår"
      ]
     ]
    },
    {
     "box": "CDA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "# flyttar 93 hit, på det valda spåret. Munkeröds del räknas som gjord.",
     "screens": [
      {
       "box": "MUN",
       "lines": [
        "93 MOTTAGET     ",
        "CDA        12:34"
       ],
       "changed": true
      },
      {
       "box": "CDA",
       "lines": [
        "93 ANK SP2      ",
        "MUN        12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    }
   ]
  },
  {
   "id": "tva-boxar",
   "title": "Två boxar på samma station",
   "mode": "Med klartecken",
   "intro": "En station kan ha en box per sida. Varje box hanterar bara tågen på sina sträckor.",
   "setup": null,
   "boxes": [
    {
     "id": "CDA-V",
     "code": "CDA",
     "label": "CDA · vänster",
     "station": "Charlottendal"
    },
    {
     "id": "CDA-H",
     "code": "CDA",
     "label": "CDA · höger",
     "station": "Charlottendal"
    },
    {
     "id": "VA",
     "code": "VA",
     "label": "VA",
     "station": "Vagnsta"
    }
   ],
   "start": [
    {
     "box": "CDA-V",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "CDA-H",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    },
    {
     "box": "VA",
     "lines": [
      "                ",
      "Nr# A:Kö   12:34"
     ],
     "changed": true
    }
   ],
   "steps": [
    {
     "box": "CDA-V",
     "keys": [
      "3",
      "9",
      "#"
     ],
     "wait": null,
     "caption": "Vänsterboxen (mot Munkeröd) söker 39, som går mot Vagnsta. Svaret blir ANNAN SIDA.",
     "screens": [
      {
       "box": "CDA-V",
       "lines": [
        "ANNAN SIDA      ",
        "           12:34"
       ],
       "changed": true
      },
      {
       "box": "CDA-H",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "VA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": [
      [
       "#",
       "OK"
      ],
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ]
     ]
    },
    {
     "box": null,
     "keys": [],
     "wait": 3,
     "caption": "Beskedet försvinner av sig självt efter tre sekunder.",
     "screens": [
      {
       "box": "CDA-V",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": true
      },
      {
       "box": "CDA-H",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "VA",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      }
     ],
     "meanings": []
    },
    {
     "box": "CDA-H",
     "keys": [
      "3",
      "9",
      "#"
     ],
     "wait": null,
     "caption": "Högerboxen hittar tåget och begär klartecken direkt.",
     "screens": [
      {
       "box": "CDA-V",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA-H",
       "lines": [
        "           39?VA",
        "*Åter B:Öv 12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA?39       1/1",
        "#Ja *Nej   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Återta begäran…"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Översikt utan trafikändring"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    },
    {
     "box": "VA",
     "keys": [
      "#"
     ],
     "wait": null,
     "caption": "Vagnsta ger klart. På Charlottendal visar bara högerboxen tåget.",
     "screens": [
      {
       "box": "CDA-V",
       "lines": [
        "                ",
        "Nr# A:Kö   12:34"
       ],
       "changed": false
      },
      {
       "box": "CDA-H",
       "lines": [
        "           39>VA",
        "#Avg *Åter 12:34"
       ],
       "changed": true
      },
      {
       "box": "VA",
       "lines": [
        "CDA>39          ",
        "C/D A:Kö   12:34"
       ],
       "changed": true
      }
     ],
     "meanings": [
      [
       "*",
       "Tillbaka"
      ],
      [
       "A",
       "Förfrågningskö (0 väntar)"
      ],
      [
       "B",
       "Placera på spår…"
      ],
      [
       "C",
       "Föregående tåg"
      ],
      [
       "D",
       "Nästa tåg"
      ]
     ]
    }
   ]
  }
 ]
};
