from __future__ import annotations


def runtime_package() -> dict:
    return {
        "schema_version": 1,
        "publication_id": "publication-2026-08-11-a",
        "published_at": "2026-08-11T08:30:00Z",
        "meet": {
            "id": "meet-a",
            "name": "Sommarträffen",
            "slug": "sommartraffen",
            "active_day": "Lör",
            "timezone": "Europe/Stockholm",
            "default_dispatch_mode": "clearance",
            "clock_time": "09:15",
        },
        "stations": [
            {"id": "station-a", "code": "CDA", "name": "Charlottendahl"},
            {"id": "station-b", "code": "LEK", "name": "Lekeberg"},
        ],
        "connections": [
            {
                "id": "connection-a-b",
                "station_a_id": "station-a",
                "station_b_id": "station-b",
                "track_type": "single",
            }
        ],
        "panels": [
            {
                "id": "panel-a",
                "station_id": "station-a",
                "name": "CDA Tambox",
                "slots": {"A": "connection-a-b", "B": None, "C": None, "D": None},
            },
            {
                "id": "panel-b",
                "station_id": "station-b",
                "name": "LEK Tambox",
                "slots": {"A": "connection-a-b", "B": None, "C": None, "D": None},
            },
        ],
        "trains": [
            {
                "id": "movement-101-a",
                "train_number": "101",
                "station_id": "station-a",
                "station": "CDA",
                "track": "1",
                "days": "Dagl",
                "arrival_time": None,
                "departure_time": "09:20",
                "arrival_from": None,
                "departure_to": "LEK",
                "sort_time": "09:20",
                "no_stop": False,
                "note": None,
                "manual_sort_order": 0,
            },
            {
                "id": "movement-101-b",
                "train_number": "101",
                "station_id": "station-b",
                "station": "LEK",
                "track": "1",
                "days": "Dagl",
                "arrival_time": "09:35",
                "departure_time": None,
                "arrival_from": "CDA",
                "departure_to": None,
                "sort_time": "09:35",
                "no_stop": False,
                "note": None,
                "manual_sort_order": 0,
            },
            {
                "id": "movement-202-a",
                "train_number": "202",
                "station_id": "station-a",
                "station": "CDA",
                "track": "2",
                "days": "Sön",
                "arrival_time": "10:10",
                "departure_time": "10:15",
                "arrival_from": "LEK",
                "departure_to": "LEK",
                "sort_time": "10:10",
                "no_stop": False,
                "note": None,
                "manual_sort_order": 0,
            },
        ],
        "routes": [
            {
                "id": "route-101-a",
                "train_number": "101",
                "station_id": "station-a",
                "station_name": "CDA",
                "stop_order": 0,
                "arrival_time": None,
                "departure_time": "09:20",
            },
            {
                "id": "route-101-b",
                "train_number": "101",
                "station_id": "station-b",
                "station_name": "LEK",
                "stop_order": 1,
                "arrival_time": "09:35",
                "departure_time": None,
            },
            {
                "id": "route-202-a",
                "train_number": "202",
                "station_id": "station-a",
                "station_name": "CDA",
                "stop_order": 0,
                "arrival_time": "10:10",
                "departure_time": "10:15",
            },
        ],
    }
