"""Server-owned TMBox copy. ASCII LCD text, never translated protocol/data.

Swedish source phrases are stable catalogue keys for the existing renderers.
Translate before composing a line, never by replacing substrings in a rendered
frame (a station/train can have the same name as a UI word).
"""
from __future__ import annotations

LANGUAGES = (("sv", "Svenska"), ("da", "Dansk"), ("nb", "Norsk"),
             ("en", "English"), ("de", "Deutsch"))

# sv | en | da | nb | de. Short ASCII labels fit HD44780 ROMs consistently.
_COPY = """C=NEXT *=BACK|C=NEXT *=BACK|C=NAESTE *=RETUR|C=NESTE *=RETUR|C=WEITER *=ZUR.
C=TAG D=SPRAK|C=TRAINS D=LANG|C=TOG D=SPROG|C=TOG D=SPRAK|C=ZUEGE D=SPR.
SAVING...|SAVING...|GEMMER...|LAGRER...|SPEICHERE...
NOT SAVED #=TRY|NOT SAVED #=TRY|IKKE GEMT #=PROV|IKKE LAGRET #=NY|FEHLER #=NEU
UPP|SET|OPSTIL|STILL|BEREIT
FORARE|CREW|FORER|FORER|PERSONAL
BEGAR|REQUEST|ANMOD|BE OM|ANFRAGE
AVGATT|DEPARTED|AFGAET|AVGATT|ABGEF.
NARMAR|APPROACH|NAERMER|NAERMER|NAHERT
ANKOMMIT|ARRIVED|ANKOMMET|ANKOMMET|ANGEK.
VANTAR|WAITING|VENTER|VENTER|WARTET
KLART|APPROVED|KLAR|KLART|ERLAUBT
EJ KLART|REFUSED|AFVIST|AVVIST|ABGELEHNT
ATERTAGEN|WITHDRAWN|TRUKKET|TRUKKET|ZURUECK
UTGANGEN|EXPIRED|UDLOBET|UTLOPT|ABGELAUFEN
FINNS EJ IDAG|NOT TODAY|IKKE I DAG|IKKE I DAG|NICHT HEUTE
SAKNAR NUMMER|ENTER NUMBER|ANGIV NUMMER|ANGI NUMMER|NUMMER FEHLT
TAGET FINNS EJ|NO SUCH TRAIN|TOG UKENDT|UKJENT TOG|ZUG UNBEKANNT
SPARET FINNS EJ|NO SUCH TRACK|SPOR UKENDT|UKJENT SPOR|GLEIS UNBEKANNT
INGEN SADAN LINJE|NO SUCH LINE|LINJE UKENDT|UKJENT LINJE|STRECKE FEHLT
LINJEN UPPTAGEN|LINE OCCUPIED|LINJE OPTAGET|LINJE OPPTATT|STRECKE BELEGT
REDAN AVGJORD|ALREADY DECIDED|ALLEREDE AFGJORT|ALLEREDE AVGJORT|SCHON ENTSCHIEDEN
REDAN KVITTERAD|ALREADY ACKED|KVITTERET|KVITTERT|SCHON BESTAETIGT
ARENDET AR BORTA|CASE NOT FOUND|SAG MANGLER|SAK MANGLER|VORGANG FEHLT
EJ ER FRAGA|NOT FOR YOU|IKKE TIL DIG|IKKE TIL DEG|NICHT FUER EUCH
EJ ER BEGARAN|NOT YOUR REQUEST|IKKE DIN SAG|IKKE DIN SAK|NICHT EURE ANFR.
BOXEN EJ KOPPLAD|BOX UNASSIGNED|BOKS IKKE KOBLET|BOKS IKKE KOBLET|BOX UNZUGEORDNET
FEL STATION|WRONG STATION|FORKERT STATION|FEIL STASJON|FALSCHER BAHNHOF
LAGET HAR ANDRATS|STATE CHANGED|STATUS AENDRET|STATUS ENDRET|STATUS GEAENDERT
INGEN TRAFF|NO MATCH|INTET MATCH|INGEN TREFF|KEIN TREFFER
FEL PROTOKOLL|WRONG PROTOCOL|FORKERT PROTOKOL|FEIL PROTOKOLL|PROTOKOLLFEHLER
OKANT KOMMANDO|UNKNOWN COMMAND|UKENDT KOMMANDO|UKJENT KOMMANDO|BEFEHL UNBEKANNT
NAT SAKNAS|NO NETWORK|INTET NETVAERK|INGEN NETT|KEIN NETZ
FORSOKER IGEN|RETRYING|PROVER IGEN|PROVER IGJEN|NEUER VERSUCH
INSTALLERA WIFI|SET UP WIFI|INDSTIL WIFI|SETT OPP WIFI|WIFI EINRICHTEN
SOKER SERVER|FINDING SERVER|SOGER SERVER|SOKER SERVER|SUCHE SERVER
ANSLUTER SERVER|CONNECTING|FORBINDER|KOBLER TIL|VERBINDE
SERVER BORTA|SERVER OFFLINE|SERVER OFFLINE|SERVER FRAKOBLET|SERVER OFFLINE
KOPPLA BOXEN|ASSIGN BOX|TILDEL BOKS|TILDEL BOKS|BOX ZUORDNEN
STATION KOPPLAD|STATION ASSIGNED|STATION TILDELT|STASJON TILDELT|BAHNHOF GEWAEHLT
BOX KOPPLAD|BOX ASSIGNED|BOKS TILDELT|BOKS TILDELT|BOX ZUGEORDNET
HAMTAR DATA...|LOADING DATA...|HENTER DATA...|HENTER DATA...|LADE DATEN...
HAMTAR PANEL...|LOADING PANEL|HENTER PANEL|HENTER PANEL|LADE PANEL
NATVERK RADERAS|CLEARING WIFI|SLETTER WIFI|SLETTER WIFI|LOESCHE WIFI
SKICKAR...|SENDING...|SENDER...|SENDER...|SENDE...
KOMMANDO OK|COMMAND OK|KOMMANDO OK|KOMMANDO OK|BEFEHL OK
KOMMANDO NEKAT|COMMAND REFUSED|KOMMANDO AFVIST|KOMMANDO AVVIST|BEFEHL ABGELEHNT
HAMTAR NYTT LAGE|REFRESHING|HENTER STATUS|HENTER STATUS|AKTUALISIERE
INGA TAG IDAG|NO TRAINS TODAY|INGEN TOG I DAG|INGEN TOG I DAG|HEUTE KEINE ZUEGE
 TAG  C=BLADDRA| TRAINS C=NEXT| TOG C=NAESTE| TOG C=NESTE| ZUEGE C=WEITER
INGET TAG VALT|NO TRAIN CHOSEN|INTET TOG VALGT|INGEN TOG VALGT|KEIN ZUG GEWAEHLT
*=TILLBAKA|*=BACK|*=TILBAGE|*=TILBAKE|*=ZURUECK
B=ANDRA|B=CHANGE|B=AENDR|B=ENDRE|B=AENDERN
INGET TILLATET|NO ACTION|INGEN HANDLING|INGEN HANDLING|KEINE AKTION
FORARE |CREW |FORER |FORER |PERSONAL 
PA PLATS|READY|KLAR|KLAR|BEREIT
SAKNAS|MISSING|MANGLER|MANGLER|FEHLT
C=NASTA  *=TILLBAKA|C=NEXT *=BACK|C=NAESTE *=RETUR|C=NESTE *=RETUR|C=WEITER *=ZUR.
VALJ SPAR|CHOOSE TRACK|VAELG SPOR|VELG SPOR|GLEIS WAEHLEN
INGA SPAR|NO TRACKS|INGEN SPOR|INGEN SPOR|KEINE GLEISE
A=VALJ  C=NASTA|A=PICK C=NEXT|A=VALG C=NAESTE|A=VELG C=NESTE|A=WAHL C=WEITER
 AV | OF | AF | AV | VON 
BEGAR MOT|REQUEST TO|ANMOD TIL|BE OM TIL|ANFRAGE AN
INGEN GRANNE|NO NEIGHBOUR|INGEN NABO|INGEN NABO|KEIN NACHBAR
A=BEGAR  C=NASTA|A=REQ C=NEXT|A=ANMOD C=NAESTE|A=BE OM C=NESTE|A=ANFR. C=WEITER
TAG|TRAIN|TOG|TOG|ZUG
A=SOK  B=SUDDA|A=FIND B=ERASE|A=SOG B=SLET|A=SOK B=SLETT|A=SUCHE B=LOESCH
SIFFROR PA TANGENT|TYPE TRAIN NO.|INDTAST TOGNR.|TAST TOGNR.|ZUGNR. EINGEBEN
*=AVBRYT|*=CANCEL|*=ANNULLER|*=AVBRYT|*=ABBRUCH
 TRAFFAR| MATCHES| MATCH| TREFF| TREFFER
C=NASTA #=VALJ|C=NEXT #=PICK|C=NAESTE #=VALG|C=NESTE #=VELG|C=WEITER #=WAHL
ANK|ARR|ANK|ANK|AN
AVG|DEP|AFG|AVG|AB
INGA ARENDEN|NO REQUESTS|INGEN SAGER|INGEN SAKER|KEINE ANFRAGEN
KLARERING |REQUEST |ANMODNING |FORESP. |ANFRAGE 
A=KLART  B=EJ|A=YES B=NO|A=JA B=NEJ|A=JA B=NEI|A=JA B=NEIN
FRAN |FROM |FRA |FRA |VON 
  *=TILLBAKA| *=BACK| *=RETUR| *=RETUR| *=ZUR.
INGA MEDDELANDEN|NO MESSAGES|INGEN BESKEDER|INGEN MELDINGER|KEINE MELDUNGEN
LINJEN LEDIG|LINE CLEAR|LINJE FRI|LINJE FRI|STRECKE FREI
A=KVITTERA|A=ACK|A=KVITTER|A=KVITTER|A=QUITTIEREN
V1-PANEL SAKNAS|V1 PANEL MISSING|V1 PANEL MANGLER|V1 PANEL MANGLER|V1 PANEL FEHLT
KOLLA SERVERN|CHECK SERVER|TJEK SERVER|SJEKK SERVER|SERVER PRUEFEN
INGET SERVER-SVAR|NO SERVER REPLY|INTET SVAR|INGEN SVAR|KEINE ANTWORT
KONTROLLERA LAGE|CHECK STATUS|TJEK STATUS|SJEKK STATUS|STATUS PRUEFEN
DISPLAY SAKNAS|DISPLAY MISSING|DISPLAY MANGLER|SKJERM MANGLER|DISPLAY FEHLT
KNAPPSATS SAKNAS|KEYPAD MISSING|TASTER MANGLER|TASTER MANGLER|TASTEN FEHLEN
KONTROLLERA I2C|CHECK I2C|TJEK I2C|SJEKK I2C|I2C PRUEFEN
UPPDATERA SERVER|UPDATE SERVER|OPDATER SERVER|OPPDATER SERVER|SERVER UPDATEN
LOKAL INMATNING|LOCAL INPUT|LOKAL INDTAST|LOKAL INNTAST|LOKALE EINGABE
Tag: |Train: |Tog: |Tog: |Zug: 
*=Avb|*=Back|*=Ret|*=Ret|*=Zur
Till: |To: |Til: |Til: |An: 
Tåg: |Train: |Tog: |Tog: |Zug: 
Väntar svar...|Awaiting reply|Afventer svar|Venter pa svar|Warte auf Antwort
Från |From |Fra |Fra |Von 
A=KLART|A=YES|A=JA|A=JA|A=JA
B=EJ|B=NO|B=NEJ|B=NEI|B=NEIN
KLAR|READY|KLAR|KLAR|BEREIT
A=Avg|A=Dep|A=Afg|A=Avg|A=Ab
Tåg ut?|Departed?|Tog afgaet?|Tog avgatt?|Abgefahren?
A=AVGÅTT|A=DEPARTED|A=AFGAET|A=AVGATT|A=ABGEF.
Avbryt begäran?|Withdraw?|Traek tilbage?|Trekk tilbake?|Zurueckziehen?
#=Ja|#=Yes|#=Ja|#=Ja|#=Ja
*=Nej|*=No|*=Nej|*=Nei|*=Nein
Ank |Arr |Ank |Ank |An 
från |from |fra |fra |von 
A=ANKOMMIT|A=ARRIVED|A=ANKOMMET|A=ANKOMMET|A=ANGEK.
"""

MESSAGES: dict[str, dict[str, str]] = {code: {} for code, _ in LANGUAGES}
for _row in _COPY.splitlines():
    _values = _row.split("|")
    assert len(_values) == 5, _row
    for _code, _value in zip(("sv", "en", "da", "nb", "de"), _values):
        MESSAGES[_code][_values[0]] = _value

# Stable protocol keys need not be the visible Swedish wording.
MESSAGES["sv"].update({"C=NEXT *=BACK": "C> #OK *=BAK",
                       "SAVING...": "SPARAR...",
                       "NOT SAVED #=TRY": "EJ SPARAT #=NY"})
for _code, _hint in (("en", "C> #OK *=BACK"), ("da", "C> #OK *=RET"),
                     ("nb", "C> #OK *=RET"), ("de", "C> #OK *=ZUR")):
    MESSAGES[_code]["C=NEXT *=BACK"] = _hint


def language_code(value: object) -> str:
    if not isinstance(value, str) or value not in MESSAGES:
        raise ValueError("Unsupported TMBox language")
    return value


def ui_payload(language: str, *, legacy: bool = False) -> dict:
    code = language_code(language)
    messages = dict(MESSAGES[code])
    if legacy:
        # ESP8266 renders traffic on the server. Only local lifecycle/input
        # copy is needed in its small RAM, not the ESP32 screen catalogue.
        needed = {"C=NEXT *=BACK", "SAVING...", "NOT SAVED #=TRY", "NAT SAKNAS", "FORSOKER IGEN", "INSTALLERA WIFI", "SOKER SERVER",
                  "ANSLUTER SERVER", "SERVER BORTA", "KOPPLA BOXEN", "BOX KOPPLAD",
                  "HAMTAR PANEL...", "KOMMANDO NEKAT", "HAMTAR NYTT LAGE",
                  "V1-PANEL SAKNAS", "KOLLA SERVERN", "INGET SERVER-SVAR", "KONTROLLERA LAGE",
                  "DISPLAY SAKNAS", "KNAPPSATS SAKNAS", "KONTROLLERA I2C",
                  "UPPDATERA SERVER", "LOKAL INMATNING", "Tag: ", "*=Avb"}
        messages = {key: value for key, value in messages.items() if key in needed}
    return {"version": 1, "language": code,
            "languages": [{"code": c, "name": n} for c, n in LANGUAGES],
            "messages": messages}


def text(language: str, key: str) -> str:
    return MESSAGES[language_code(language)].get(key, key)
