// Every authored text in Server's pages exists in all five languages
// (tools/i18n-audit.mjs). TKL runs the same rules in its own npm test.
const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const repo = path.resolve(__dirname, '../..');
const load = () => import(path.join(repo, 'tools/i18n-audit.mjs'));
const show = (entries) => entries.slice(0, 25).map((entry) => `${entry.missing ? entry.missing.join(',') + ' ' : ''}${JSON.stringify(entry.source)}\n    ${entry.places[0]}`).join('\n');

test('every visible text in Server, US and TMBox pages has en, sv, da, nb and de', async () => {
  const {audit} = await load();
  const result = await audit({tkl: null});
  assert.deepEqual(Object.keys(result), ['server web', 'US pages', 'terminal16']);
  for (const [surface, {strings, missing, unwrapped}] of Object.entries(result)) {
    assert.ok(strings > 100, `${surface}: the audit found only ${strings} texts`);
    assert.equal(missing.length, 0, `${surface}: add these to translations/ui.txt (or tmbox.txt, us_web/workspace-messages.js):\n${show(missing)}`);
    assert.equal(unwrapped.length, 0, `${surface}: these are written to the page without t():\n${show(unwrapped)}`);
  }
});

test('every page script is audited or has a reason not to be', async () => {
  const {SURFACES} = await load();
  const audited = new Set(Object.values(SURFACES).flatMap((surface) => [...surface.html, ...surface.js, ...surface.catalog]));
  const reasons = {
    'i18n.js': 'the runtime itself', 'i18n-init.js': 'calls initializeStatic', 'qrcode.js': 'a QR encoder, no text',
    'us-cloud-messages.js': 'a catalogue', 'tmbox-messages.js': 'a catalogue',
    // The in-app TMBox client (#tmbox-v2-view) cannot be reached: #tmbox redirects to /tmbox/.
    'tmbox-fixtures.js': 'unreachable in-app TMBox view', 'tmbox-legacy-catalog.js': 'unreachable in-app TMBox view',
    'tmbox-guide.js': 'unreachable in-app TMBox view', 'tmbox-render.js': 'unreachable in-app TMBox view',
    'tmbox-nav.js': 'unreachable in-app TMBox view', 'tmbox-attention.js': 'unreachable in-app TMBox view',
    // Generated by scripts/tmbox_flows.py from the Swedish 16x2 engine; the page says so.
    'flows.js': 'generated flows of a Swedish box',
  };
  for (const dir of ['web', 'us_web', 'terminal16_web']) {
    for (const name of fs.readdirSync(path.join(repo, 'src/tmbox_gateway', dir)).filter((file) => /\.(js|html)$/.test(file))) {
      const file = path.join(repo, 'src/tmbox_gateway', dir, name);
      assert.ok(audited.has(file) || reasons[name], `${dir}/${name} is neither audited nor excused in this test`);
    }
  }
});

test('the extraction follows web/i18n.js: what it translates must have a row', async () => {
  const {jsStrings, htmlStrings, htmlTemplateStrings, isLanguage} = await load();
  const kinds = (source) => Object.fromEntries(jsStrings(source).map((item) => [item.source, item.kind]));
  const found = kinds(`
    const label = (node, source) => { node.dataset.tmText = source; node.textContent = t(source); };
    const NAMES = { a: "Från tabell" };
    el.textContent = t("Spara nu");
    el.title = t(ok ? "Ja tack" : "Nej tack");
    label(el, "Via hjälpare");
    el.textContent = t(NAMES[key]);
    el.textContent = "Rakt in";
    el.textContent = t(\`Byggd \${name}\`);
    throw new Error(payload.message || "Det gick inte");
    console.log("Värden för loggen");
    const note = "En mening utan t()";
    el.className = "tm-btn tm-btn--sm";
  `);
  assert.equal(found['Spara nu'], 't()');
  assert.equal(found['Ja tack'], 't()');
  assert.equal(found['Nej tack'], 't()');
  assert.equal(found['Via hjälpare'], 'label()');
  assert.equal(found['Från tabell'], 't(NAMES[…])');
  assert.equal(found['Rakt in'], 'unwrapped');
  assert.equal(found['Byggd ${…}'], 'unwrapped');
  assert.equal(found['Det gick inte'], 'Error()');
  assert.equal(found['Värden för loggen'], undefined);
  assert.equal(found['tm-btn tm-btn--sm'], undefined);
  assert.equal(found['En mening utan t()'], 'literal');
  assert.deepEqual(htmlTemplateStrings(['<p title="Hjälp">Hej ', ' där</p><code>kod</code>']).map((item) => item.source), ['Hjälp', 'Hej', 'där']);
  const page = htmlStrings('<body><p>Text <b>fet</b></p><span data-no-i18n>Charlottendal</span><svg><path/></svg><input placeholder="Sök" data-tm-placeholder="Sök"></body>');
  assert.deepEqual(page.map((item) => item.source), ['Text', 'fet', 'Sök']);
  for (const neutral of ['TMBox', 'CDA', '12:34', '{count}', 'TrainMeet Server', '/us/conductor', 'https://example.org']) assert.equal(isLanguage(neutral), false, neutral);
});
