// Reuses the original TrainMeet dictionaries and overlays reviewed UI terms.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = path.join(repo, 'translations');
const flat = (obj, prefix = '', result = {}) => { for (const [key,value] of Object.entries(obj)) typeof value === 'string' ? result[prefix + key] = value : flat(value, prefix + key + '.', result); return result; };
const original = {};
for (const [id, name] of [['sv','sv'],['en','en'],['da','da'],['nb','no'],['de','de']]) original[id] = flat(JSON.parse(fs.readFileSync(path.join(source, `legacy-${name}.json`))));
const messages = {};
const parameters = (text) => [...text.matchAll(/\{(\w+)\}/g)].map((match) => match[1]).sort().join(',');
// Preserve parameter spelling in uppercase headings.
const upper = (text, locale) => text.split(/(\{\w+\})/g).map((part) => /^\{\w+\}$/.test(part) ? part : part.toLocaleUpperCase(locale === 'nb' ? 'nb-NO' : locale)).join('');
for (const [id, value] of Object.entries(original.sv)) {
  if (value.includes('<') || value.includes('{{')) continue;
  const row = Object.fromEntries(Object.entries(original).filter(([, dict]) => dict[id]).map(([locale, dict]) => [locale, dict[id]]));
  messages[value] = row;
  if (row.en) messages[row.en] = row;
}
for (const line of ['ui.txt', 'release.txt'].flatMap((file) => fs.readFileSync(path.join(source, file), 'utf8').split('\n'))) {
  if (!line.trim() || line.startsWith('#')) continue;
  const fields = line.split('|');
  if (fields.length !== 5 || fields.some((field) => !field)) throw new Error('Expected en|sv|da|nb|de: ' + line);
  if (fields.some((field) => parameters(field) !== parameters(fields[0]))) throw new Error('Translation parameters differ: ' + line);
  const row = Object.fromEntries(['en','sv','da','nb','de'].map((locale,index) => [locale,fields[index]]));
  for (const value of [row.en,row.sv]) {
    messages[value] = row;
    messages[upper(value, 'en')] = Object.fromEntries(Object.entries(row).map(([key,value]) => [key,upper(value,key)]));
  }
}
// Source aliases share rows rather than repeating every five-language object.
// This keeps the offline catalog smaller for Raspberry Pi clients as well.
const rows = [], indices = new Map(), aliases = {};
for (const [source, row] of Object.entries(messages)) {
  const encoded = JSON.stringify(row);
  if (!indices.has(encoded)) { indices.set(encoded, rows.length); rows.push(row); }
  aliases[source] = indices.get(encoded);
}
fs.writeFileSync(path.join(repo, 'src/tmbox_gateway/web/i18n-messages.js'), '// Generated by tools/build-i18n.mjs. Edit translations/ui.txt.\n(() => {\nconst rows = ' + JSON.stringify(rows) + ';\nconst aliases = ' + JSON.stringify(aliases) + ';\nglobalThis.TrainMeetMessages = Object.fromEntries(Object.entries(aliases).map(([source, index]) => [source, rows[index]]));\n})();\n');
console.log(`${Object.keys(messages).length} source messages`);
